# mntCustomData downstream REST client
quarkus.rest-client.mnt-custom-data-api.url=${MNT_CUSTOM_DATA_URL:http://localhost:4501}
quarkus.rest-client.mnt-custom-data-api.scope=jakarta.inject.Singleton
quarkus.rest-client.mnt-custom-data-api.connect-timeout=5000
quarkus.rest-client.mnt-custom-data-api.read-timeout=5000

